### ISSUE TITLE
Any option to trigger with code hide/show

### ISSUE THREAD

**Issue by sdkcarlos** [ctrlmaniac/sidebar#11]
Actually you can trigger only with the given selector : 

``` javascript
$('#searchbar-right').simplerSidebar({
                        opener: '#oce-toolbar-find',
                        sidebar: {
                            align: 'right', //or 'right' - This option can be ignored, the sidebar will automatically align to right.
                            width: 200, //You can ignore this option, the sidebar will automatically size itself to 300px.
                            closingLinks: '.close-sidebar' // If you ignore this option, the plugin will look for all links and this can be buggy. Choose a class for every object inside the sidebar that once clicked will close the sidebar.
                        },
                        mask:{
                            css:{
                                opacity :0
                            }
                        }
                    });
```

There`s any method to trigger something like ? $.simplerSidebar.show(); or .hide(); ?

**Comment by dcdeiv** [comment]
Can you please explain me what you want to achieve?

**Comment by sdkcarlos** [comment]
Hide or show the sidebar without user interaction a Method like showSidebar and hideSidebar. This sidebar is very useful and i need to trigger these actions without user interaction

**Comment by dcdeiv** [comment]
By now there isn't such feature. I guess you should think of a trick by yourself.
However I will consider to add a feature like this in the next version of this plugin!

**Comment by sdkcarlos** [comment]
A quick & dirty solution for who need this too is to hide the opener with css and trigger the click event with jQuery : $("#opener").trigger("click");

Thanks for take the time to answer !

**Comment by dcdeiv** [comment]
Can you please provide me some examples? Like the way you did this trick?
I am willing to add this options so I am rewriting the plugin, it will be awesome if you'd explain me your situation!

**Comment by sdkcarlos** [comment]
I mean, for example : I have an asynchronous call (ajax) and it will get some data from the server , when this data is fetched I need to open the sidebar with pure javascript ! 

We need actually to open the bar ,click on the given selector : 

`selector.simplerSidebar({opener:'#otherselector'});`

![screenshot_2016-02-21-10-24-58](https://cloud.githubusercontent.com/assets/11634719/13201908/68fe7218-d885-11e5-8d0d-f6e655aabd2f.png)

I used this plugin in Our Code Editor Free, an android app so in the simple case , a normal initialization worked.

But in other project I needed to trigger the bar when the akax call finished so I simply used : 

`$("#otherselector").trigger("click");`

That did the trick for me , with the actual source Code of your project , a good possible fix to this is add some option like :

`selector.simplerSidebar("show");`

When executed, check if the plugins has been already initializated on the selector and show the bar, otherwise initalize it.
However this is just a suggestion and the plugin is working very well, with the trigger function the problem is solved (if someone needs the same Feature).

**Comment by dcdeiv** [comment]
This sounds a little complicated to me, but I will think of how to implement this feature!

**Comment by dcdeiv** [comment]
This is painful using the jquery plugin pattern. And since other patterns I tested lack of the ability to run truly multiple instances, I think that by triggering the click like you did is the best option!

I won't close this issue because I really committed to find the way that can coexist with jquery!

**Comment by dmorrison** [comment]
I would like to see this feature implemented too. Thanks for the useful plugin!

**Comment by dcdeiv** [comment]
The only smart way to toggle the animation is by triggering the trigger like @sdkcarlos did!
