### ISSUE TITLE
Triggerless run 

### ISSUE THREAD

**Issue by HashRocketSyntax** [ctrlmaniac/sidebar#35]
Here there. Thanks for the lib =) I have been using this successfully in my html for several months. 

Now I am wondering if I can run this within another js function. Here I have an ajax call and I want to fire the sidebar as part of the ajax success function. 

The thing that I am clicking on is within a canvas - so there is no html element for the required trigger.

```
...
success: function (response) {
                        console.log("AJAX call NeedEmployeeData made successfully!")

                        $( "#sidebar-main" ).simplerSidebar( {
                            attr: "sidebar-main",
                            selectors: {
                                trigger: "", // <--- problem?
                                quitter: ".close-right-panel"
                            },
                            animation: {
                                easing: "easeOutQuint"
                            },
                            mask: {
                                display: true
                            }
                        });
...
```

Funny thing is... it works on the first click... kind of. But it appears on the left with no mask. It does **ease out** though - so the quitter seems to work! Subsequent clicks don't slide it back onto the page from the right side of the window, but I can see it over there if I try to scroll off the page.

First click img https://imgur.com/a/n85PEl7

**Comment by dcdeiv** [comment]
I think that this is related to #11

The sidebar is bonded to a click event. Have you tried to trigger the click event instead of calling the sidebar again?

I am thinking of this feature but unluckly I don't have many time to make new features. Any help it's appreciated!
